name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'LayoutEngine/publish/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LayoutEngine/publish/**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            runtime: win10-x64
          - os: ubuntu-latest
            runtime: linux-x64
  
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        # select a 'version' from https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/6.0/releases.json
        dotnet-version: 6.0.100-preview.6.21355.2
        include-prerelease: true
    - name: build
      run: dotnet build LayoutEngine/LayoutEngine.csproj --configuration CI --runtime ${{ matrix.runtime }}
    - name: chmod artifact executable
      run: |
          if [ ${{ matrix.runtime }} = linux_x64 ]; then
               sudo chmod 755 './LayoutEngine/publish/LayoutEngine'
          fi
    - name: build test
      run: dotnet build LayoutEngine.Tests/LayoutEngine.Tests.csproj --configuration CI --runtime ${{ matrix.runtime }}
    - name: test
      run: dotnet test --configuration CI --runtime ${{ matrix.runtime }}
      timeout-minutes: 5
